### PR TITLE
Fix leak in HybiParser

### PR DESCRIPTION
**Pull request by elevenfive**
In strict mode, was getting warning:

java.lang.Throwable: Explicit termination method 'end' not called
   at dalvik.system.CloseGuard.open(CloseGuard.java:184)
   at java.util.zip.Inflater.<init>(Inflater.java:82)

### CODE REVIEW

**Comment by elevenfive** [comment]
@koush sorry for the regression!  If you have time to explain the issue, I'm definitely interested to hear more.

**Comment by koush** [comment]
https://github.com/koush/AndroidAsync/issues/482#issuecomment-246641959

**Comment by koush** [comment]
See the previous comment. Not sure I understand what is going on. Let me read the RFC now. https://tools.ietf.org/pdf/draft-tyoshino-hybi-websocket-perframe-deflate-05.pdf

**Comment by koush** [comment]
Actually I think I understand what is going on now. See this commit:

https://github.com/elevenfive/AndroidAsync/commit/1b7f44cd463aa1dcfe6bd5a682c15ca21e0352b5

**Comment by koush** [comment]
The RFC (and other implementations I've seen) distinguish between payload data and application data (which seems to be a subset of the payload). It's been a while since I've touched this code, but that may be the issue?

The other change I noticed, is that you are no longer reusing the same inflater instance between frames. That actually seems correct, but I am unsure. That may also be related to the regression.

The actual underlying exception is not being wrapped, which is problematic.

**Comment by elevenfive** [comment]
ty....  is the revert in 2.1.9?

**Comment by koush** [comment]
I have reverted the change, but not published a build yet.

**Comment by koush** [comment]
It seems the leak was to fix a strict mode issue? Do you have a full stack of this error?

I am not sure if end even needs to be called, if the inflater is reused between frames (I'm not sure if this is the case).

**Comment by elevenfive** [comment]
```
E/StrictMode: A resource was acquired at attached stack trace but never released. 
See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'end' not called
    at dalvik.system.CloseGuard.open(CloseGuard.java:180)
    at java.util.zip.Inflater.<init>(Inflater.java:82)
    at com.koushikdutta.async.http.HybiParser.<init>(HybiParser.java:68)
    at com.koushikdutta.async.http.WebSocketImpl$1.<init>(WebSocketImpl.java:74)
    at com.koushikdutta.async.http.WebSocketImpl.setupParser(WebSocketImpl.java:74)
    at com.koushikdutta.async.http.WebSocketImpl.finishHandshake(WebSocketImpl.java:195)
    at com.koushikdutta.async.http.AsyncHttpClient$11.onConnectCompleted(AsyncHttpClient.java:676)
    at com.koushikdutta.async.http.AsyncHttpClient.reportConnectedCompleted(AsyncHttpClient.java:170)
    at com.koushikdutta.async.http.AsyncHttpClient.access$200(AsyncHttpClient.java:51)
    at com.koushikdutta.async.http.AsyncHttpClient$4.setDataEmitter(AsyncHttpClient.java:385)
    at com.koushikdutta.async.http.AsyncHttpResponseImpl.emitter(AsyncHttpResponseImpl.java:73)
    at com.koushikdutta.async.http.HttpTransportMiddleware$2.onStringAvailable(HttpTransportMiddleware.java:120)
    at com.koushikdutta.async.LineEmitter.onDataAvailable(LineEmitter.java:45)
    at com.koushikdutta.async.Util.emitAllData(Util.java:23)
    at com.koushikdutta.async.AsyncSSLSocketWrapper.onDataAvailable(AsyncSSLSocketWrapper.java:233)
    at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:220)
    at com.koushikdutta.async.Util.emitAllData(Util.java:23)
    at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
    at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
    at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)
```

**Comment by koush** [comment]
This seems like an erroneous strictmode exception to be honest. This inflater is operating entirely in memory, so it is not as if a file stream is left dangling.

I think the easiest fix here is to add a finalizer to HybiParser and call end on the inflater there. That's the lowest impact change. Make sure to guard it with a try/catch as well.

**Comment by koush** [comment]
Here's how the closeguard is handled. Looks like the inflater is a native implementation. It gets salty if not ended manually. So yeah, I guess just call end() in the finalizer of HybiParser.
https://android.googlesource.com/platform/libcore.git/+/android-4.2.2_r1/luni/src/main/java/java/util/zip/Inflater.java

**Comment by elevenfive** [comment]
ty - in case you didn't see I have PR for fix: https://github.com/koush/AndroidAsync/pull/486

**Comment by kLkA** [comment]
Hey, could you explain how to sync gradle and get fix? 

Im using this string
`compile "com.koushikdutta.async:androidasync:2.+"`
but still experiencing issue with 

```
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err: java.io.IOException: Invalid deflated data
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.http.HybiParser.emitFrame(HybiParser.java:407)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.http.HybiParser.access$800(HybiParser.java:46)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.http.HybiParser$5.onDataAvailable(HybiParser.java:203)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.DataEmitterReader.handlePendingData(DataEmitterReader.java:24)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.DataEmitterReader.onDataAvailable(DataEmitterReader.java:41)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
09-29 15:22:19.293 11362-11534/computician.janusclient W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)
```

**Comment by elevenfive** [comment]
@kLkA 

```
./gradlew clean build --refresh-dependencies
```

**Comment by ziyuyun** [comment]
I also encounter this error

10-27 09:58:54.549 24072-24273/com.example.liujianghao.myapplication W/System.err: java.io.IOException: Invalid deflated data
10-27 09:58:54.550 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.http.HybiParser.emitFrame(HybiParser.java:407)
10-27 09:58:54.550 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.http.HybiParser.access$800(HybiParser.java:46)
10-27 09:58:54.550 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.http.HybiParser$5.onDataAvailable(HybiParser.java:203)
10-27 09:58:54.551 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.DataEmitterReader.handlePendingData(DataEmitterReader.java:24)
10-27 09:58:54.551 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.DataEmitterReader.onDataAvailable(DataEmitterReader.java:41)
10-27 09:58:54.552 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
10-27 09:58:54.552 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
10-27 09:58:54.553 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
10-27 09:58:54.553 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
10-27 09:58:54.553 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
10-27 09:58:54.553 24072-24273/com.example.liujianghao.myapplication W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)

**Pull request closed without merging**
