### PR TITLE
Update build; Fix NPE; Fix Leak

### PR DESCRIPTION
**Pull request by elevenfive**
- Build Tools 24.0.0
- Add Gradle wrapper and use Gradle 2.14
- Android Gradle Plugin 2.1.2
- Fix leak & NPE

### CODE REVIEW

**Comment by koush** [comment]
Isn't the inflater supposed to be reused between messages? Dictionary continually gets updated?

**Comment by elevenfive** [comment]
Thanks for the reply @koush!  The javadocs are:

```
    /**
     * Releases resources associated with this {@code Inflater}. Any unused
     * input or output is discarded. This method should be called explicitly in
     * order to free native resources as soon as possible. After {@code end()} is
     * called, other methods will typically throw {@code IllegalStateException}.
     */
```

Unfortunately I'm not well versed on the internal operation of this lib -- do you know where the inflater can be safely closed besides the finishing of each deflation?  Upon HybiParser#onDisconnect perhaps?

**Comment by koush** [comment]
Looks like the inflater operation is supposed to be confined to every frame... new instance of an inflater per frame.
https://tools.ietf.org/id/draft-tyoshino-hybi-websocket-perframe-deflate-05.txt

If you can clean up the diff to only the changes in the java files (please don't introduce newline changes), I'll take the pull request.

**Comment by koush** [comment]
Actually this is fine.

**Comment by koush** [comment]
I should have looked at the original changes more thoroughly. The inflater shouldn't be in the hybiparser.

**Pull request merged**
