### PR TITLE
Redirected requests now keep the same request method, body and headers a...

### PR DESCRIPTION
**Pull request by glennporter-examtime**
...s the original one.

This pull request is to address a problem found when handling redirects. The HTTP method of the new request always defaults to GET unless the original one is HEAD; and headers and body of the original request are not included in the new one either.

There may be a better way of doing this but it works for me :)

### CODE REVIEW

**Comment by koush** [comment]
Looks good. Been meaning to do this for a whole, but what nervous about implications. Will test and see.

**Comment by koush** [comment]
https://github.com/koush/AndroidAsync/commit/d9975f4f5b51ccc3f3dcfaca0221f8cd0639ddbb

Can't enable this by default, because most web forms accept a POST and then redirect.

**Comment by koush** [comment]
I think preserving headers makes sense, but preserving the body is probably a bad idea.

**Comment by koush** [comment]
Does your use case also require the body?

**Comment by glennporter-examtime** [comment]
Hi @koush, what actually brought about me making this change was that our web app is moving to a new domain shortly and in the interim requests to the new API are redirected to the old API so that everything continues to work before the switchover. We need to maintain the body in the redirected request because without it, the API endpoint won't be able to do anything with the POST. Would you not say that the request body would also be needed in the new request for nearly all other cases of redirecting a POST? Thanks!

**Comment by koush** [comment]
Browsers and most web services do not behave that way. A common flow for web forms:
POST to a /submit page with a body
The /submit page redirects to another page (to prevent refresh based resubmission). This new page is a GET.
Redirect to /finished page.

Redirecting a form body (and headers) across domains, is also a potential data leak.

On form redirects:
http://www.w3.org/wiki/HTML_forms_-_the_basics#hidden_form_inputs

**Comment by glennporter-examtime** [comment]
Our case is a 307 redirect actually, rather than a 301 (I didn't even think to make this distinction when I made my code change). According to http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection, 307 redirects should remain a POST if the original request was a post. Could we even change it to retain the method type, headers and body under the condition that it is a 307?

**Comment by koush** [comment]
Ah yeah, 307 would be fine

**Pull request merged**
